name: Tests

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '5 1 * * *'  # every day at 01:05
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    timeout-minutes: 45
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
        pyv: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.pyv }}

    - uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: pyproject.toml

    - name: install
      run: uv pip install -e ".[dev]" "dvc[testing] @ git+https://github.com/iterative/dvc" --system

    - name: lint
      timeout-minutes: 10
      uses: pre-commit/action@v3.0.1

    # https://github.com/iterative/pytest-servers/pull/122
    # https://github.com/abiosoft/colima/issues/468
    # https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#cannot-connect-to-the-docker-daemon-at-unixvarrundockersock-is-the-docker-daemon-running
    # colima v0.5.6 seems to run more stable than the latest - that has occasional network failures (ports are not open)
    # see: https://github.com/abiosoft/colima/issues/962
    - name: Use colima as default docker host on MacOS
      if: runner.os == 'macOS'
      run: |
        brew install docker lima || true # avoid non-zero exit code if brew link fails
        sudo curl -L -o /usr/local/bin/colima https://github.com/abiosoft/colima/releases/download/v0.5.6/colima-Darwin-x86_64
        sudo chmod +x /usr/local/bin/colima
        colima start
        sudo ln -vsf "${HOME}"/.colima/default/docker.sock /var/run/docker.sock
      env:
        HOMEBREW_NO_AUTO_UPDATE: true
        HOMEBREW_NO_INSTALL_CLEANUP: true
        HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: true
        HOMEBREW_NO_INSTALL_UPGRADE: true

    - name: run tests
      timeout-minutes: 40
      run: pytest -v -n=auto --cov-report=xml --cov-report=term

    - name: upload coverage report
      uses: codecov/codecov-action@v5
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
